#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.
#we can also use the number 15 that is the  number of signal SIGTERM

trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
