#!/usr/bin/env bash
#display Best scholl 10 times using while loop
#in line 8  displays Best School and then Hi on a new line.
i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i == 8 ];then
		echo "Hi"
	fi
	((i++))
done
