#!/usr/bin/env bash
#display Best scholl 10 times using while loop
#in line 8  displays Best School and then Hi on a new line.
i=1
while [ $i -le 10 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
