#!/usr/bin/env bash
#display Best scholl 10 times using while loop
#in line 8  displays Best School and then Hi on a new line.
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
